### ISSUE TITLE
Servidor no inicia con traducción instalada

### ISSUE THREAD

**Issue by iam-danless** [ByAlexTTV/Dawncraft-Espanol#1]
Buenas, antes quiero agrader por el trabajo de traducir este modpack.

Te comento, ejecuto el script del servidor en PowerShell y me retorna el mensaje:
"Failed to load datapacks, can't proceed with server load. You can either fix your datapacks or reset to vanilla with --safeMode"

El servidor funciona correctamente sin la traducción, incluso sobreescribiendo con los archivos originales después del fallo.

Intenté volver a generar el mundo con la traducción, sin éxito.

Adjunto log para más información.
[latest.log](https://github.com/user-attachments/files/16576730/latest.log)

**Comment by ByAlexTTV** [comment]
Lo siento mucho que no funcione pero la traducción es antigua no funciona con nuevas versiones. El tutorial funciona bien pero usa otros archivos en la página del mod en CurseForge especifica que versión es.
https://www.curseforge.com/minecraft/modpacks/dawn-craft
